#!/usr/bin/env bash
# CCBridge — .claude/rules/ generation

generate_rules() {
    local mountpoint="$1"
    local ssh_target="$2"
    local remote_path="$3"
    local probe_output="$4"

    local rules_dir="${mountpoint}/.claude/rules"
    local rules_file="${rules_dir}/ccbridge-remote.md"

    mkdir -p "$rules_dir"

    # Parse probe data
    local os_info="" kernel="" arch="" remote_shell="" hostname=""
    local python_ver="" node_ver="" go_ver="" rust_ver="" java_ver="" gcc_ver=""
    local pkg_managers="" docker_ver="" git_ver=""
    local project_files="" project_type="" git_branch="" git_remote=""
    local services="" cpu_cores="" memory="" disk_usage=""

    while IFS= read -r line; do
        case "$line" in
            OS_INFO=*)       os_info="${line#OS_INFO=}" ;;
            KERNEL=*)        kernel="${line#KERNEL=}" ;;
            ARCH=*)          arch="${line#ARCH=}" ;;
            REMOTE_SHELL=*)  remote_shell="${line#REMOTE_SHELL=}" ;;
            HOSTNAME=*)      hostname="${line#HOSTNAME=}" ;;
            CPU_CORES=*)     cpu_cores="${line#CPU_CORES=}" ;;
            MEMORY=*)        memory="${line#MEMORY=}" ;;
            PYTHON_VER=*)    python_ver="${line#PYTHON_VER=}" ;;
            NODE_VER=*)      node_ver="${line#NODE_VER=}" ;;
            GO_VER=*)        go_ver="${line#GO_VER=}" ;;
            RUST_VER=*)      rust_ver="${line#RUST_VER=}" ;;
            JAVA_VER=*)      java_ver="${line#JAVA_VER=}" ;;
            GCC_VER=*)       gcc_ver="${line#GCC_VER=}" ;;
            PKG_MANAGERS=*)  pkg_managers="${line#PKG_MANAGERS=}" ;;
            DOCKER_VER=*)    docker_ver="${line#DOCKER_VER=}" ;;
            GIT_VER=*)       git_ver="${line#GIT_VER=}" ;;
            PROJECT_FILES=*) project_files="${line#PROJECT_FILES=}" ;;
            PROJECT_TYPE=*)  project_type="${line#PROJECT_TYPE=}" ;;
            GIT_BRANCH=*)    git_branch="${line#GIT_BRANCH=}" ;;
            GIT_REMOTE=*)    git_remote="${line#GIT_REMOTE=}" ;;
            SERVICES=*)      services="${line#SERVICES=}" ;;
            DISK_USAGE=*)    disk_usage="${line#DISK_USAGE=}" ;;
        esac
    done <<< "$probe_output"

    # Build language versions section
    local lang_section=""
    [ "$python_ver" != "not installed" ] && [ -n "$python_ver" ] && lang_section="${lang_section}- Python: ${python_ver}\n"
    [ "$node_ver" != "not installed" ] && [ -n "$node_ver" ] && lang_section="${lang_section}- Node.js: ${node_ver}\n"
    [ "$go_ver" != "not installed" ] && [ -n "$go_ver" ] && lang_section="${lang_section}- Go: ${go_ver}\n"
    [ "$rust_ver" != "not installed" ] && [ -n "$rust_ver" ] && lang_section="${lang_section}- Rust: ${rust_ver}\n"
    [ "$java_ver" != "not installed" ] && [ -n "$java_ver" ] && lang_section="${lang_section}- Java: ${java_ver}\n"
    [ "$gcc_ver" != "not installed" ] && [ -n "$gcc_ver" ] && lang_section="${lang_section}- GCC: ${gcc_ver}\n"
    [ -z "$lang_section" ] && lang_section="- No language runtimes detected\n"

    # Build project info
    local project_section=""
    if [ -n "$project_type" ]; then
        project_section="- **Type**: ${project_type}\n"
    fi
    if [ -n "$project_files" ]; then
        # Remove trailing comma
        project_files="${project_files%,}"
        project_section="${project_section}- **Root files**: ${project_files}\n"
    fi
    if [ -n "$git_branch" ]; then
        project_section="${project_section}- **Git branch**: ${git_branch}\n"
    fi
    if [ -n "$git_remote" ] && [ "$git_remote" != "none" ]; then
        project_section="${project_section}- **Git remote**: ${git_remote}\n"
    fi
    if [ -n "$disk_usage" ] && [ "$disk_usage" != "Unknown" ]; then
        project_section="${project_section}- **Disk usage**: ${disk_usage}\n"
    fi

    # Extract host from ssh_target
    local ssh_host="${ssh_target#*@}"

    # Build SSH command prefix (with sshpass if password auth)
    local ssh_prefix="ssh"
    local ssh_opts="-p ${SSH_PORT:-22}"
    if [ -n "${SSH_PASS:-}" ]; then
        ssh_prefix="sshpass -p \"\$SSH_PASS\" ssh"
    fi
    if [ -n "${SSH_KEY:-}" ]; then
        ssh_opts="${ssh_opts} -i ${SSH_KEY}"
    fi

    # Write the rules file
    cat > "$rules_file" <<RULES_EOF
# CCBridge Remote Execution Rules
# Auto-generated by CCBridge on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Safe to delete — will be regenerated on next \`ccbridge\` connect.

## CRITICAL: Remote Execution Context

This project is mounted from a remote server via SSHFS. Files are directly readable/writable,
but ALL shell commands must execute on the remote server via SSH.

## Command Execution

For ANY command that needs to run in the project context (build, test, install, git, etc.):

\`\`\`bash
${ssh_prefix} ${ssh_opts} ${ssh_target} "cd ${remote_path} && <command>"
\`\`\`

### Quick Reference

| Action | Command |
|---|---|
| Run command | \`${ssh_prefix} ${ssh_opts} ${ssh_target} "cd ${remote_path} && <command>"\` |
| Run tests | \`${ssh_prefix} ${ssh_opts} ${ssh_target} "cd ${remote_path} && npm test"\` |
| Install deps | \`${ssh_prefix} ${ssh_opts} ${ssh_target} "cd ${remote_path} && pip install -r requirements.txt"\` |
| Git operations | \`${ssh_prefix} ${ssh_opts} ${ssh_target} "cd ${remote_path} && git status"\` |
| Start service | \`${ssh_prefix} ${ssh_opts} ${ssh_target} "cd ${remote_path} && docker-compose up -d"\` |
| View logs | \`${ssh_prefix} ${ssh_opts} ${ssh_target} "tail -f /var/log/syslog"\` |
| Long-running cmd | \`${ssh_prefix} ${ssh_opts} ${ssh_target} "cd ${remote_path} && nohup ./run.sh &"\` |

### File Operations

- Reading and editing files: use directly (SSHFS handles it), no SSH wrapper needed
- File permissions or bulk file ops: prefer SSH for performance
- Large files (>100MB): use SSH commands on remote to avoid SSHFS overhead

### Do NOT

- Do NOT run build/compile commands locally — the local Mac environment differs from remote Linux
- Do NOT install project dependencies locally — install on remote via SSH
- Do NOT assume local environment variables apply — use SSH to read remote env
- Do NOT use local paths in commands — always use the remote path: \`${remote_path}\`

## Remote Environment

- **Server**: ${ssh_host} (${hostname})
- **OS**: ${os_info}
- **Kernel**: ${kernel}
- **Arch**: ${arch}
- **Shell**: ${remote_shell}
- **CPU**: ${cpu_cores} cores
- **Memory**: ${memory}

### Languages & Runtimes

$(echo -e "$lang_section")

### Package Managers

${pkg_managers:-None detected}

### Docker

${docker_ver}

### Git

${git_ver}

### Active Services

${services:-No relevant services detected}

## Project Overview

$(echo -e "$project_section")
RULES_EOF

    echo "✓ Generated $rules_file"

    # Update .gitignore
    update_gitignore "$mountpoint"
}

update_gitignore() {
    local mountpoint="$1"
    local gitignore="${mountpoint}/.gitignore"

    if [ -f "$gitignore" ]; then
        if ! grep -q "ccbridge-remote.md" "$gitignore" 2>/dev/null; then
            echo "" >> "$gitignore"
            echo "# CCBridge remote execution rules (auto-generated)" >> "$gitignore"
            echo ".claude/rules/ccbridge-remote.md" >> "$gitignore"
            echo "✓ Updated .gitignore"
        fi
    fi
}

cleanup_rules() {
    local mountpoint="$1"
    rm -f "${mountpoint}/.claude/rules/ccbridge-remote.md"
    echo "✓ Removed ccbridge-remote.md"
}
