# CCBridge Remote Execution Rules
# Auto-generated by CCBridge on {{GENERATED_AT}}
# Safe to delete — will be regenerated on next `ccbridge` connect.

## CRITICAL: Remote Execution Context

This project is mounted from a remote server via SSHFS. Files are directly readable/writable,
but ALL shell commands must execute on the remote server via SSH.

## Command Execution

For ANY command that needs to run in the project context (build, test, install, git, etc.):

```bash
ssh -p {{SSH_PORT}} {{SSH_TARGET}} "cd {{REMOTE_PATH}} && <command>"
```

### Quick Reference

| Action | Command |
|---|---|
| Run command | `ssh -p {{SSH_PORT}} {{SSH_TARGET}} "cd {{REMOTE_PATH}} && <command>"` |
| Run tests | `ssh -p {{SSH_PORT}} {{SSH_TARGET}} "cd {{REMOTE_PATH}} && npm test"` |
| Install deps | `ssh -p {{SSH_PORT}} {{SSH_TARGET}} "cd {{REMOTE_PATH}} && pip install -r requirements.txt"` |
| Git operations | `ssh -p {{SSH_PORT}} {{SSH_TARGET}} "cd {{REMOTE_PATH}} && git status"` |
| Start service | `ssh -p {{SSH_PORT}} {{SSH_TARGET}} "cd {{REMOTE_PATH}} && docker-compose up -d"` |
| View logs | `ssh -p {{SSH_PORT}} {{SSH_TARGET}} "tail -f /var/log/syslog"` |
| Long-running cmd | `ssh -p {{SSH_PORT}} {{SSH_TARGET}} "cd {{REMOTE_PATH}} && nohup ./run.sh &"` |

### File Operations

- Reading and editing files: use directly (SSHFS handles it), no SSH wrapper needed
- File permissions or bulk file ops: prefer SSH for performance
- Large files (>100MB): use SSH commands on remote to avoid SSHFS overhead

### Do NOT

- Do NOT run build/compile commands locally — the local Mac environment differs from remote Linux
- Do NOT install project dependencies locally — install on remote via SSH
- Do NOT assume local environment variables apply — use SSH to read remote env
- Do NOT use local paths in commands — always use the remote path: `{{REMOTE_PATH}}`

## Remote Environment

- **Server**: {{SSH_HOST}} ({{HOSTNAME}})
- **OS**: {{OS_INFO}}
- **Kernel**: {{KERNEL}}
- **Arch**: {{ARCH}}
- **Shell**: {{REMOTE_SHELL}}
- **CPU**: {{CPU_CORES}} cores
- **Memory**: {{MEMORY}}

### Languages & Runtimes

{{LANGUAGE_VERSIONS}}

### Package Managers

{{PKG_MANAGERS}}

### Docker

{{DOCKER_VER}}

### Git

{{GIT_VER}}

### Active Services

{{SERVICES}}

## Project Overview

{{PROJECT_INFO}}
